import { Property, Agent } from '@/types';

// ─── Property Images (from mockup) ───────────────────────────────────────────
const IMG = {
  villa1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBnVQfCtu9Dd90Gdaa2jDdkQ2z_Xeq6krQV6VJSeeyr13PvW80MmDQcH-QeJC6-1GKkzV5nE8eC-oB960jNWV5NYzaMhoQgOBB_ED4LDUKHYjKwZsumdyys8aRuChvRvDjuHfbLGt1QSdJYKQAeL8abuA-5Ig01BoaOcMtiY0uz_ScZ6QCDlYyJ86LBji7ohI7-8f8rVevJejxSG_Ix29FhghbOU5HOZO5N5eNnpEQybQLaXXWyNNLP6GDDoAs0pkHE0QaBbHYyynY',
  apt1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAEG4UY5u0JElfjVLxxUDcApdi6LfUqZ6Z7yQy4JP4A73UNkROOWN5LaxwcMf5TX23nAntOc5JrNrD7H5QxJ-mXsXwkR8awpeMWwvcKI54PcNSYpVA3cBMPyl5loeeQX1SxgK-Y7a1-tQaDg-l0cDSoxC3Ep9x7EUczKuVGdv9by0ZJu_b2INL3KwrDpFt7edqLFFa8c-OiiCwl47md7p6dOsSwlPBQ2ECuN-WhMhs84ILnrq_Gzb1hZSzh7FraRi-recHtJL7ibuA',
  villa2: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBIr1OJ9-yNWsnpX0bj_JTFPfAqiQfdW1DCcvxmuTa9I2_6HkmRugI8M7_0uRI36cC8ZjR7fL4LQPxr2jE50SiptwKOQgJ7aSba4LVRD972rhiemVtdCk5vkTMaxEjGs06bXbnCnWnk1VEU98jb0yl8m0-Dqd3ZwmS8xsg7j0G4mVa7v_77VXCw4rvVGNUiK0yJ4oTtCh3bZkdjK-7jbcVS6WLzW7lbwmjSHnoIvlNCZZVgeMtMfjLwyU4mEdb1B-kZPnDmN_J8MZc',
  lodge1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBuoAWuM1VGtt0M6sfYM0R2MKcGERXtHyzypVYYTdsAYb0stm2ZNjcjVU6-3HqUN64MHkWVIOCcIN8jg8YnJSU9F12yUtEsokrFI4CWHucMW21MdW-OeYMBAXiF-0Y0MiPQiZAotLuzy_L_uFF6Qpeq_OR4USHBusnt4KAWkAANjQTf1_bAWyqdFJau6tVdFrSHhHpUQgIuemnIo-bzpIwUaT2tokCoQwLVXiWnngoAn8TKjytfUtcAjeKLoWEHvfTHabnHTDkPzUA',
  villa3: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCvZjT_7aV2itnLH8EEDzTPea_imLtpZCJdZZlMqtQ_HHoZ7npw5606WHV3OuJ4uFHiZUQm78FuE8nrwCIwka1jFDe-RYbFSBW5S9poXDun_PvXEsg20-INJWl3eiuPQHjEb-LvDnOnxHOc3XyiKzX51bU88RH36Co5EyCiDpoa5bQ2u9vkx5aUmkYTG5269XF15_vWs8foAp9ilSm2XOQfe276844Mid4TAngsnwcux9cw7OCRCfZxH83tFZedGibhaMUCBFqsMMk',
  loft1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuApliVjyyP7V3JSXWkyUmWNm0NvNNaNRvsd05QEZGmJbD2-rgbKrTamqcBP-5jVVtr5DwqtZYW2X1-bJC2cxS6JKPnlu6NYwPMBz0z2EJVfcNFJ6wM38SQa0pdX94TFKtExtWQwnmj69Pzt_KzgUkkboWYLoD51clkFy-MATWkGPE25UA2vIi6XQrNru_7zyZ5-QqAIMg1mt2eEKDPgu7m-A0vpAlYAKceo2QNXQkRD6sHTg5Jf2Kn5a1XBVcOrVkJbtHM4HvcW-Gw',
  bungalow1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBXmVXfrR9gDEAxBqg_CTDrBGtwjigvXUegpzjOUwy5_KhKDwqLQUoiDw1AnMe5I63bQtYCVfymjKE8PIy0e4ubXLEyV6XG8sB7wDMzHMNfckuxXWBBDx5K2ZTHS-8buN49uPS_fDNiNj2X7_f8UXDhvqhIm0BUDrlhHm9YI53Dp2CnNXlOQjyBvwVK2_eFDjSF7sJuOxomNWTDhWR_SSn8VN4LhVRumluTtLeOBAX2MdOcvy0Fxe4bIk_-11Wu8QmDjqHywbLDE90',
  kitchen1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBW9txYValHhGBwEhxtNiTzmBvX9wupqMPVeADauZ0KKimshVC92Uuec7B8F8j6G1ZhkKBHv_3PekABQ3rydVWvsxCm0BuXTbCdSh138d8Ur2WZOtn4drgDpnM5Y3dAFxYUtQHxhpTm-rfW23nvFOgx38X08cuonjv08DoFJ-JkxA6c09FKKreJRID45_RF6eturyuslMl4jPsk1ePATlLIPi-0joyYNYtlRpNQRq3ltegaN_9nF-golT73aX8HhLjk06gh2eR65jY',
  penthouse1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAkEyite999R_f_UtPMhdQ-IzL79PzmSFEk_01vn9W1UBAICdCyefUMGnnKZ_oeyc7KqdSO1bvv4gvQLryy-oti7gGTgGLz1MJz_Ra__iZv6bgdUPFvSAcuEuiRORodGMloXyr2-IIDfhtmu9fEf3ik9kz3qm2IbH869QUGcdpcKuztZ598inuMBhX0QRQg7l13RkvJajiGybS0DZLT93HQ9DcVOCjmpC1XK6cDO574P1uGPzmgJCLzcxLHLsNxy9UDwbGk5DeDm8Q',
  suite1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAtn5vMSitMxw1Nx-t8iHxHZaWd-nfMxm-rRJzCMz3SqetHqDYqIxIstyydaz3QIVxWXfLPGC-PjnOY9zFuknn8jwhfRLYsT2v0z_Rv8Y9YP6tIR9_vIQEmhv1rO5zeak3SknTvAQqp9ngpUaEFWA19xZJz5M_nYp9EKtvOces6pxW6SlU3PA5zep7GUiBq5QXAHmmpNc3bHpR5gzuk3Hh8mZsBerHDa0PVZ8eL2pkhnrIi2wXAVyWuPA8ELihybtUUzmSz5obG_1E',
  house1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCIn8wOk1EZcRHEeC3vcD9eA0wOBI_Fw87f2KkWOD1FI43lo-8ciaDCLYC9Veb5HsBQrNalEbkd6S8TcmtdAtSUk5_UX_z9Tr-HdseqhfFxQGGBaCwvpBK2P8gRqtDhGetTu8CMO4L1gbGqyArg6KCOBTuYsfxhfSPNHtyHnsnY8528MEm8MFPSd86yun8V2tUAq00qcZxY7_S1GAAcIGrIDFEpO4ZndfZ_mf-2Z4lxQE7ldG2u57iOloAGok12KOzXSlD2mHgWBJ4',
  estate1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuArBvmjRXQl4F4rVWdfk9rNN6MKEe3yx108BXGYFT3rqggjIzqU1abd-q_BmkgXff-s77ViovfqBLrgYSSDb4HHJ6pVFi6JH2_W5THZQYwl5zdZWMS0QPq4rkOJBGo6Vq9UOOjPw0apb_WQohv6Eq0m3oTMw7Tn-4Ex2MTwIvtt41ZfEg1HM2Cwk4syHdls9j1Hn6LvdN6yECxqXw1lFdi_s2fZZBhmiQZmzsCDtEGGm9ZJtujh1DV57McUAy56whinPuxAlJzVhjo',
  estate2: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdPvtwBFRJZ0reUz94GFXZgh-tjFnMQUpiHF_qpyEELiYXW-tXSIhgrzsDEpsyVkRCzRjLw_K0NwvUpXN2CRPjDxHvfmsMHA-Us2V6_4xh7u-4yI0cWn85E3pAJkqi6WDcP8X42t2V73y9uTtdS9Q1IhstBeIke3DR4oYOSUvUjcNX0kUhYnWD1YLNDOjzGzHO7nlBLA63GUvQoVTSGZWNo-2n40-ucH8qwVxlzGHHCsVTxXSPF3a8fd7BDrloErlTGqvzX6wj1vM',
  coastal1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCejGbZKce27jP1QYoeuiS5r1VzSBzSu8aIKfEX57ggicU6Vrt6cTDPNkNa-WP2YpHVWjDSMe0aiJzI3MBob2Kx1Gsq3WUlgkf1xj2f6odXlD7OXdepDSpMc2Kdbtocwdeqt_EhaRk9m7303fJtxGbphN7etd9VT4S4nUA5X5BA-CMDACJ0D98FY7hFn1qMf9Z5pMgl0HnZzMhWlUaeqyIMbfzdIlZxA_J8WUwkDWxwpgDzjxOD2Oi_8dO8BIv34L7GjgqatbYyAmg',
  manor1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCzl8gP26wDJ6slGfE6ome_oouncH_O1yUvdez8MZ_x102DcNkFjdxkc7jDzogIfOGIJ-o3waNVeZZWlM34IpmRO79kgWcHtyt5M8CeVMnnHhxef2iQ3jcE-6L0OuIrwllLH0aJcZ8Ipyoy4oo3YSw1Hf2kNcMV8nVc-patPlJTBmGDwF81OZxtRS2PdGfCnVdKGyzxSm67aGO0yWm5aZPWcWPedpr0we9UqxA_7JT8LqW67cvILITlc9nVrhCKSgVYOu-psju5pto',
  villa4: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvv-ne1xWEVCUWvKaM9xHnqC3AKnJV8UntM7o3NJWft6uL3rEXLbv6v70v0V30zJcmi5quqIqDfLW6IJRvaZ3Bj46cbiGvCgYwOxlQpYzbPIn8fE8I1Zt-E6hJXKtkgd3n8wdg_-hRYbSuzVv7HsStcG5iCcLMVxrSqTy5vnsn3rdBSNT9kqxgrtnP55OqRJJfLNrHB7u6bj4OPSgK2_TO8jAQt-CXI5LiRFmMmjhFOBamG0IPKN2OWFU-qTwbiq6XjQHyo4Jy-5I',

  // Property detail images
  detail1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD31WvUyYYNyBppmeohY2nEzvSqOc1hUCkbHjl9c96v6ZyDht8fKfIV5wUtx2RW7v59EFS_8WlaxqEHliufdzesXcxXAK3rsweahmnc6WHTuWC7B9n7_l1Wat5_uPP_2xrSjG47Bg_V64jxJww56if1qDsssqf5TLJUGwILfINDkJrWsX7o-_EtsRzdNf09uYnMFi6WQ77DENQs6JIiz1qD7EcgmSwg79Np4HpwcPFhl5Bad1amO3t_IvCTcWlxaZoc3SL0jd8BKQg',
  detail2: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCKaczPYOYJKpKEGKL9p7PcgkR_w-EK2RUPhe4s_8TA3QqWh4Xve_UcdtYNlwFjbTwZPio-bytyTkqhxGWTttu5DglcDqEsf4iUXhvVu-olSJIWlA9-mDnWXpHoVkcQDiBDt3bn0fTw7WK9K5chhLk8ot-YYGz-xpNlPjV7h_g9kVaBMYEx54q69Axw_ALm8XnNAvU35_EPcFMWxc9SLCG1KYAlY56VPRf08TADuLhQ_4Ds3v5qG68ABT_Gl1uk04t5U38ohxRj7us',
  detail3: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDgGRkaLJTiSF2By0n3mzH6iFzW2uf6mIIfDPaFqsDPlkqdYbaKZu6qbZ_Nnh72gtL0BkOP7DV2qHpcYzJ-V5aqvXQBG6jSoqAGJNgwlWlLeZAeo9n02HvKMJDe0wWFaYMUppUW0RrYWF59moxdNxG-uSYfT8qBYDUmlqkCNSx8wct9xUlT5S7tLne1fQ6svR9IpIUFkZbEsHqvMqaRavEjn8fxh-FYQWTWNzctcbMlpYvNZw3OYDZWSeMiJp9dPPwwghNfqifkTpo',
  detail4: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCwlemTtKfpa0Frzh6dqS__qEivCaiSrn93qs_MDMFPuxI-O4jXkRYd8LXqohl0m1X55Cxiqc1VXeqSP-_FAyMSruWVyaLQkTxrE8nEVmNT8Q1gP8GdMeLDR7roz4tW-6bi4hfxVngvbX_a1YhcvaIVmcsaB1uz0QtjUt8oo9cc0lDKmBIBXj214F3TUdP3UKe5ujY5pjlPiX5ULDRmFHeIz3I0HqC_Vh6Q3pGLAZn9kZUNpyhUqmohdFWiZv0u3c_mogLUW4ny6MU',
  detail5: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJYV9dyn_NYEyRhDODwdZpKIz62lmJclrFFXX39XLTUfBQjqEfaW2HGDATFafYixzRFv0cFqywY89IfIGuY2nhWRVyYNGAeCuE3igQohgw3QnN1csXDFK1dW1vrqYffN_SLK9Ng0bm_P2JkUX2Obrsmt1vk25x8bHODxkQD2TowXjjqOOC5OLKaHkuB6EP1e_kXXaHpcWrz7FW9ak1-_05QcKnoA23B_GZAL4SH9jKEpwayiOgpCGVX2oPGbPqbWGqlDT6wDUH-Ek',

  // Agents
  agent1: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-UWszFojBQMnfF2uvy3LdjaqkLPnDrDeRGPbNQ2Xm8BiXVWrkLEhaBXQdHTjTXoKeXyD1K2uZ1l_RWxD-N_-cwzfopMlvQGSqWReJ16YJRjteY4EXzk2u4PDEnCVDnyhcOsqKlkS_SeTDcOxuUH4wqYmJU9EF9FSDwQhNPRFgQTRGHYB_8UL9ySnCzAZ22tDEtb2vG68wSzqH12WAlIzJ-pdel1yP231BEGrPAk_mBScoIkzda9T_JrHowCEyZXCo9sVehCi8dY4',
  agent2: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB_XORlXOuI-zytboO7e3nPqBchkwsDrt4cvNw2uQDx-S-GnS9ywG6uKmfXg0BogZGO8f6UE2aQ3eDa3LCRCm9FRC3PEvr6C5yY7PXrdmHyTiUQsrC9ge_8QWDabYd0OBR9wexqasjI0zHov_upG2VBKN2RE60-ou6sCDwaO-dumK4mRsYReTkYIQ2NteUGID1ZULizgovZY9q_cVJ7bLFwC5RJYaCZdgaDZc2cWEX6yt2ocO2oEodREch4lLqBsGL1GTr1pGttBBk',
  agent3: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5E-g-kHWfNpYJPSBNz5sF5daOk6WT1v7_Qrw53xEoGd8GBiK0qXmNmdVuRaxcMeD5oQZUWygQ8qVvR9Bw69urnqIIkley3dojdVSB3oxk2Fk_ubzhol6stI37xda1VW4t7A3PQZY-o0Ku5B3Okt__FzM2cHQzat8CkWjsADpmAWdSADcgODvoVxi42vYTPm-lWiNrH4mmYBAa98WftH3kV1UUFH_lTTX-RqlFtWOyhs1dWXtSWCJxRXOmftrsoSaPSgC7S0opULo',
  agent4: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAwOG84ysMfvx7FtCIyL8iSwB_6tyPlH3-2fDo7dxr4ZbPlktRinsAutMmA73F4l60Tgme8hmjSY0dYtY2CCCV9J27xFQhDTZHm8CWOekiVlVCtZxMhv3wmISqNztgytWdXP7WH3y0XBIC2KE2-U2nDiKwE5eMg3RiLgPLbJKpHGsIayDJ4G6k9S02MFtEXjiAXkFx2Sr-2_D-v66ac28wHYnqk5BDvtoCsHzuWod9ao9KV_-3I8aGMD9MSrpiYlVFb-svXq1bGD0',
  agent5: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCgKuvpQ8QTbvBjXAkXzV-wktut4GyMuAaFJlRUBB0eGuCKzicr5mO5ZuOD_jjbSJ8KiKyNo9WPMSVg4FZmvy6_Zb7F_baVbTD66ItNmfiGL1K6N2oqkh0JtpLgwRMQMS-MWtCxqGRm3b19szrbMuv-HuJqVkG4ocOEagwgci9ldEWDW5gF56enPwpOMZnXjKKyQcom0pLNmie4bdBeLunh1k-BJyncKOBnp81nawxOEa38_SeLatO1Qz0QL9_MSFp9pcL0pZhs_00',
  agent6: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDkPnuIw0oqmgDpTQxukqSlLM87JnVXByauWMJdt3OoCbe_ZXO7_OtJFJwXibs4Jlis6WBXb9YRI5tCoPaMI8MGZ_XsgUHd5yaLp_APC-s9MgSOb7l9QDEcluQflE-lwQo0i64IY2dyCCTW6_afjK_F8PPTGWy_dXl9jE0oBmi3C-eQ_hOruAKfT2Xb8ac4H5ofPPNPWZ-YCzRUKpVSZ3URLblas33Y5XShRTJAGdHzQeErcOwty9HJV0UMpowTP2m-RL7SYogNeaM',
};

// ─── Properties ──────────────────────────────────────────────────────────────
export const properties: Property[] = [
  {
    id: '1',
    title: 'Modern 3BR Villa in Polana',
    location: 'Polana Cimento, Maputo, Mozambique',
    city: 'Maputo',
    price: 4500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 3,
    area: 450,
    rating: 4.95,
    reviewCount: 120,
    isFeatured: true,
    isSuperhost: true,
    isRareFind: true,
    badge: 'Superhost',
    images: [IMG.detail1, IMG.detail2, IMG.detail3, IMG.detail4, IMG.detail5],
    description: `Experience the pinnacle of Maputo living in this architecturally significant villa located in the heart of the historic Polana district. Designed with a focus on seamless indoor-outdoor living, the property features floor-to-ceiling glass walls that disappear to merge the living area with a lush, tropical private garden.

The interior is a masterclass in modern minimalism, featuring Portuguese marble flooring, custom mahogany cabinetry, and a chef's kitchen equipped with the latest European appliances. Every detail has been curated to provide an atmosphere of serene luxury, from the automated lighting system to the climate-controlled wine cellar.

Polana Cimento is Maputo's most prestigious neighborhood, known for its quiet tree-lined streets, architectural heritage, and proximity to the city's finest restaurants and diplomatic missions.`,
    amenities: ['Fiber Optic WiFi (500Mbps)', '24/7 Professional Security', 'Private Designer Gym', 'Secure Underground Parking (3 slots)', 'In-unit Washer & Dryer', 'Centralized Air Conditioning', 'Infinity Pool', 'Wine Cellar', 'Home Automation', 'Tropical Garden'],
    houseRules: ['Check-in: 3:00 PM - 8:00 PM', 'No smoking allowed', 'Pets allowed on request', 'Quiet hours after 10:00 PM'],
    hostId: 'agent-1',
    tags: ['Featured', 'Luxury'],
  },
  {
    id: '2',
    title: 'Polana Sands Villa',
    location: 'Maputo City, Mozambique',
    city: 'Maputo',
    price: 450000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 3,
    area: 380,
    rating: 4.9,
    isFeatured: true,
    badge: 'Featured',
    images: [IMG.apt1, IMG.detail2, IMG.loft1],
    description: 'A stunning modern villa in the prestigious Polana neighborhood, featuring spacious living areas, a private pool, and lush tropical gardens. Perfect for families seeking luxury in Mozambique\'s capital.',
    amenities: ['Swimming Pool', '24/7 Security', 'Parking', 'Garden', 'Air Conditioning', 'Modern Kitchen'],
    hostId: 'agent-2',
    tags: ['Featured', 'For Sale'],
  },
  {
    id: '3',
    title: 'Bazaruto Azure Retreat',
    location: 'Inhambane, Mozambique',
    city: 'Inhambane',
    price: 2500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 280,
    rating: 4.85,
    isFeatured: true,
    images: [IMG.villa2, IMG.bungalow1, IMG.kitchen1],
    description: 'A breathtaking contemporary villa with stunning ocean views, a large private deck, and an infinity pool overlooking the crystal-clear waters of Bazaruto Bay.',
    amenities: ['Ocean View', 'Infinity Pool', 'Private Deck', 'WiFi', 'Air Conditioning', 'Housekeeping'],
    hostId: 'agent-3',
    tags: ['Rent'],
  },
  {
    id: '4',
    title: 'Tofo Surf Lodge',
    location: 'Praia do Tofo, Inhambane',
    city: 'Inhambane',
    price: 120,
    priceUnit: 'nightly',
    type: 'Lodge',
    listingType: 'Short Stay',
    bedrooms: 2,
    bathrooms: 1,
    area: 85,
    rating: 5.0,
    isGuestFavorite: true,
    images: [IMG.lodge1, IMG.bungalow1, IMG.kitchen1],
    description: 'A charming boutique lodge steps from the famous Tofo beach surf break. Perfect for surfers, divers and beach lovers looking for an authentic Mozambican beachside experience.',
    amenities: ['Beach Access', 'Surfboard Rental', 'WiFi', 'Outdoor Shower', 'Garden', 'Breakfast Available'],
    hostId: 'agent-5',
    tags: ['Short Stay', 'Beach'],
  },
  {
    id: '5',
    title: 'Pemba Ocean Heights',
    location: 'Cabo Delgado, Mozambique',
    city: 'Pemba',
    price: 1250000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 6,
    bathrooms: 5,
    area: 850,
    rating: 4.9,
    isFeatured: true,
    isPremium: true,
    badge: 'Premium',
    images: [IMG.villa3, IMG.detail1, IMG.manor1],
    description: 'An ultra-modern waterfront mansion in Pemba offering panoramic views of the Indian Ocean. This architectural gem features 6 bedrooms, a private helipad, and direct beach access.',
    amenities: ['Helipad', 'Private Beach', 'Infinity Pool', 'Smart Home', 'Home Theater', 'Wine Cellar', '24/7 Security'],
    hostId: 'agent-1',
    tags: ['Premium', 'Luxury', 'For Sale'],
  },
  {
    id: '6',
    title: 'Sommerschield Loft',
    location: 'Maputo Central, Mozambique',
    city: 'Maputo',
    price: 1800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 160,
    rating: 4.85,
    isFeatured: true,
    images: [IMG.loft1, IMG.apt1, IMG.kitchen1],
    description: 'A chic industrial loft in the heart of Sommerschield, Maputo\'s trendiest neighborhood. Open-plan living, exposed brick walls, and designer furnishings create a unique urban sanctuary.',
    amenities: ['WiFi', 'Air Conditioning', 'Parking', 'Gym Access', 'Rooftop Terrace', 'Concierge'],
    hostId: 'agent-4',
    tags: ['Rent', 'Urban'],
  },
  {
    id: '7',
    title: 'Vilanculos Sanctuary',
    location: 'Vilanculos, Inhambane',
    city: 'Vilanculos',
    price: 350,
    priceUnit: 'nightly',
    type: 'Bungalow',
    listingType: 'Short Stay',
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    rating: 4.95,
    isGuestFavorite: true,
    isFeatured: true,
    images: [IMG.bungalow1, IMG.kitchen1, IMG.villa2],
    description: 'An exquisite tropical sanctuary in Vilanculos, gateway to the Bazaruto Archipelago. Wake up to stunning ocean views and embark on world-class diving and sailing adventures.',
    amenities: ['Beach Access', 'Pool', 'Dhow Safaris', 'Snorkeling', 'WiFi', 'Full Kitchen', 'Garden'],
    hostId: 'agent-5',
    tags: ['Short Stay', 'Beach'],
  },
  {
    id: '8',
    title: 'Sommerschield Heights Villa',
    location: 'Sommerschield, Maputo',
    city: 'Maputo',
    price: 1250000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 3,
    area: 420,
    isFeatured: true,
    images: [IMG.estate1, IMG.detail1, IMG.apt1],
    description: 'A modern minimalist villa in Maputo with floor to ceiling glass windows and a luxury infinity pool. This is the pinnacle of Maputo residential luxury.',
    amenities: ['Infinity Pool', '24/7 Security', 'Smart Home', 'Garden', 'Parking', 'Air Conditioning'],
    hostId: 'agent-2',
    tags: ['Featured', 'For Sale'],
  },
  {
    id: '9',
    title: 'The Polana Presidential Suite',
    location: 'Polana Cimento, Maputo',
    city: 'Maputo',
    price: 850000,
    priceUnit: 'sale',
    type: 'Penthouse',
    listingType: 'Buy',
    bedrooms: 3,
    bathrooms: 2,
    area: 210,
    images: [IMG.estate2, IMG.detail2, IMG.penthouse1],
    description: 'Contemporary luxury estate with colonial architecture influence and sprawling manicured gardens in Maputo\'s most prestigious address.',
    amenities: ['Ocean View', 'Concierge', 'Pool Access', 'Parking', 'Air Conditioning', 'Smart Home'],
    hostId: 'agent-1',
    tags: ['For Sale'],
  },
  {
    id: '10',
    title: 'Coastal Breeze Residences',
    location: 'Costa do Sol, Maputo',
    city: 'Maputo',
    price: 620000,
    priceUnit: 'sale',
    type: 'Apartment',
    listingType: 'Buy',
    bedrooms: 2,
    bathrooms: 2,
    area: 180,
    images: [IMG.coastal1, IMG.apt1, IMG.kitchen1],
    description: 'A spacious modern apartment with a balcony overlooking the Indian Ocean coastline. Perfect for those who desire coastal living in Mozambique\'s capital.',
    amenities: ['Ocean View', 'Balcony', 'Pool', 'Parking', 'Security', 'Air Conditioning'],
    hostId: 'agent-4',
    tags: ['For Sale', 'Ocean View'],
  },
  {
    id: '11',
    title: 'Matola Royal Estate',
    location: 'Matola, Maputo Province',
    city: 'Matola',
    price: 2100000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 6,
    bathrooms: 5,
    area: 850,
    isNew: true,
    badge: 'New Listing',
    images: [IMG.manor1, IMG.estate1, IMG.villa3],
    description: 'An exclusive gated community mansion with private tennis court, home theater, wine cellar, and sprawling landscaped grounds. The ultimate in Mozambican luxury living.',
    amenities: ['Tennis Court', 'Home Theater', 'Wine Cellar', 'Swimming Pool', 'Guest House', 'Staff Quarters'],
    hostId: 'agent-2',
    tags: ['New Listing', 'For Sale', 'Luxury'],
  },
  {
    id: '12',
    title: 'Baixa Historic Manor',
    location: 'Baixa, Maputo',
    city: 'Maputo',
    price: 545000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 2,
    area: 280,
    images: [IMG.estate2, IMG.manor1, IMG.house1],
    description: 'A charming colonial-style boutique home with large veranda and bougainvillea in Maputo\'s historic Baixa district. A rare piece of Mozambican architectural heritage.',
    amenities: ['Garden', 'Veranda', 'Parking', 'Storage', 'High Ceilings', 'Original Features'],
    hostId: 'agent-6',
    tags: ['For Sale', 'Heritage'],
  },
  // --- Beira ---
  {
    id: '13',
    title: 'Beira Waterfront Loft',
    location: 'Macuti, Beira',
    city: 'Beira',
    price: 1200,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 1,
    area: 120,
    rating: 4.8,
    images: [IMG.loft1, IMG.apt1, IMG.kitchen1],
    description: 'Modern waterfront loft in Beira\'s prestigious Macuti district. Features panoramic ocean views and industrial-chic interiors.',
    amenities: ['Ocean View', 'Rooftop Lounge', '24/7 Security', 'Secure Parking'],
    hostId: 'agent-3',
    tags: ['Rent', 'Port-side'],
  },
  {
    id: '14',
    title: 'The Beira Executive Mansion',
    location: 'Central, Beira',
    city: 'Beira',
    price: 750000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 5,
    bathrooms: 4,
    area: 550,
    rating: 4.9,
    images: [IMG.manor1, IMG.villa1, IMG.detail2],
    description: 'Stately executive mansion in the heart of Beira. Perfect for diplomatic residence or a large family seeking luxury and security.',
    amenities: ['Private Pool', 'Guest Wing', 'Triple Garaging', 'Lush Tropical Garden'],
    hostId: 'agent-8',
    tags: ['For Sale', 'Executive'],
  },
  // --- Nampula ---
  {
    id: '15',
    title: 'Nampula Skyline Penthouse',
    location: 'Central, Nampula',
    city: 'Nampula',
    price: 2200,
    priceUnit: 'monthly',
    type: 'Penthouse',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 3,
    area: 240,
    rating: 4.85,
    images: [IMG.penthouse1, IMG.suite1, IMG.detail4],
    description: 'Nampula\'s premier residential address. This penthouse offers unmatched city views and ultra-modern amenities in the northern hub.',
    amenities: ['City View', 'Private Entrance', 'Concierge', 'Gym Access'],
    hostId: 'agent-10',
    tags: ['Rent', 'Northern Hub'],
  },
  {
    id: '16',
    title: 'Mussoma Highlands Estate',
    location: 'Nampula outskirts',
    city: 'Nampula',
    price: 480000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 3,
    area: 400,
    rating: 4.75,
    images: [IMG.estate1, IMG.house1, IMG.detail5],
    description: 'Expansive family estate set in the serene highlands of Nampula. Features local granite architecture and modern interior finishes.',
    amenities: ['Large Acreage', 'Borehole Water', 'Solar Power', 'Stunning Monolith Views'],
    hostId: 'agent-10',
    tags: ['For Sale', 'Nature'],
  },
  // --- Tete ---
  {
    id: '17',
    title: 'Zambezi River Residence',
    location: 'Bairro da Moeda, Tete',
    city: 'Tete',
    price: 1500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 320,
    rating: 4.7,
    images: [IMG.villa4, IMG.detail1, IMG.kitchen1],
    description: 'Executive villa overlooking the majestic Zambezi river in Tete. Specifically designed for corporate employees seeking comfort in the industrial capital.',
    amenities: ['River View', 'Centralized Cooling', 'Generator Backup', 'Swimming Pool'],
    hostId: 'agent-9',
    tags: ['Rent', 'Corporate'],
  },
  {
    id: '18',
    title: 'Tete Mining Hub Executive Apts',
    location: 'Central Tete',
    city: 'Tete',
    price: 320000,
    priceUnit: 'sale',
    type: 'Apartment',
    listingType: 'Buy',
    bedrooms: 2,
    bathrooms: 2,
    area: 140,
    rating: 4.6,
    images: [IMG.apt1, IMG.loft1, IMG.detail2],
    description: 'High-yield investment opportunity in Tete. Fully furnished modern apartments in the most secure part of the city.',
    amenities: ['Fully Furnished', 'Security Gate', 'Swimming Pool', 'Property Management'],
    hostId: 'agent-9',
    tags: ['For Sale', 'Investment'],
  },
  // --- Pemba ---
  {
    id: '19',
    title: 'Pemba Bay View Luxury',
    location: 'Paquitequete, Pemba',
    city: 'Pemba',
    price: 3500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 4,
    area: 450,
    rating: 4.95,
    isSuperhost: true,
    images: [IMG.villa2, IMG.detail1, IMG.detail3],
    description: 'Stunning contemporary villa in Pemba Bay. Features floor-to-ceiling windows and an infinity pool that merges with the horizon.',
    amenities: ['Infinity Pool', 'Staff Quarters', 'Solar Power', 'Helipad Access'],
    hostId: 'agent-12',
    tags: ['Rent', 'Luxury', 'Superhost'],
  },
  {
    id: '20',
    title: 'Wimbe Beachfront Retreat',
    location: 'Wimbe Beach, Pemba',
    city: 'Pemba',
    price: 1500000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 5,
    bathrooms: 5,
    area: 600,
    rating: 4.9,
    images: [IMG.villa3, IMG.estate2, IMG.detail2],
    description: 'The ultimate Pemba beach house. Direct access to the pristine sands of Wimbe Beach and extensive entertainment decks.',
    amenities: ['Private Beach Access', 'Home Theater', 'Boat Shed', 'Security'],
    hostId: 'agent-5',
    tags: ['For Sale', 'Beachfront'],
  },
  // --- Vilanculos / Additional Inhambane ---
  {
    id: '21',
    title: 'Bazaruto Dunes Lodge',
    location: 'Vilanculos Beach',
    city: 'Vilanculos',
    price: 250,
    priceUnit: 'nightly',
    type: 'Lodge',
    listingType: 'Short Stay',
    bedrooms: 1,
    bathrooms: 1,
    area: 80,
    rating: 4.95,
    images: [IMG.bungalow1, IMG.kitchen1, IMG.detail3],
    description: 'Secluded romantic lodge hidden among the dunes of Vilanculos. Features a private plunge pool and steps leading to the ocean.',
    amenities: ['Private Plunge Pool', 'Direct Beach Access', 'Romantic Setting', 'Eco-friendly'],
    hostId: 'agent-5',
    tags: ['Short Stay', 'Vilanculos'],
  },
  {
    id: '22',
    title: 'The Tofo Cliff Mansion',
    location: 'Praia do Tofo',
    city: 'Inhambane',
    price: 950000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 4,
    area: 500,
    rating: 5.0,
    isFeatured: true,
    images: [IMG.estate1, IMG.detail1, IMG.detail5],
    description: 'Dramatically perched on the cliffs of Tofo, this villa offers 270-degree ocean views and architect-designed interiors.',
    amenities: ['Clifftop Views', 'Infinity Pool', 'Observation Deck', 'Guest House'],
    hostId: 'agent-5',
    tags: ['For Sale', 'Exclusive'],
  },
  // --- Additional Beira ---
  {
    id: '23',
    title: 'Macuti Luxury Suites',
    location: 'Macuti Beach, Beira',
    city: 'Beira',
    price: 1800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    images: [IMG.apt1, IMG.detail3, IMG.kitchen1],
    description: 'Executive suites with direct access to Macuti Beach. Features high-end finishes and secure underground parking.',
    amenities: ['Beach Access', 'Gym', 'Underground Parking', '24/7 Security'],
    hostId: 'agent-3',
    tags: ['Rent', 'Beachfront'],
  },
  {
    id: '24',
    title: 'Chaimite Corporate Villa',
    location: 'Chaimite, Beira',
    city: 'Beira',
    price: 3500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 320,
    images: [IMG.villa1, IMG.detail2, IMG.loft1],
    description: 'A spacious villa designed for corporate housing in one of Beira\'s safest gated communities.',
    amenities: ['Swimming Pool', 'Generator', 'Staff Quarters', 'Gated Community'],
    hostId: 'agent-8',
    tags: ['Rent', 'Corporate'],
  },
  // --- Additional Nampula ---
  {
    id: '25',
    title: 'Nampula Business Lofts',
    location: 'Avenida Eduardo Mondlane, Nampula',
    city: 'Nampula',
    price: 1500,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 1,
    bathrooms: 1,
    area: 95,
    images: [IMG.loft1, IMG.detail4, IMG.kitchen1],
    description: 'Stylish lofts in Nampula\'s financial district. Perfect for consultants and business travelers.',
    amenities: ['High-speed WiFi', 'Cleaning Service', 'Security', 'Central Location'],
    hostId: 'agent-10',
    tags: ['Rent', 'Business'],
  },
  {
    id: '26',
    title: 'Muhala Presidential Villa',
    location: 'Muhala, Nampula',
    city: 'Nampula',
    price: 520000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 5,
    bathrooms: 4,
    area: 480,
    images: [IMG.villa4, IMG.estate2, IMG.detail5],
    description: 'A grand estate in the Muhala district, offering expansive gardens and modern luxury in Northern Mozambique.',
    amenities: ['Large Garden', 'Private Pool', 'Solar System', 'Garage'],
    hostId: 'agent-10',
    tags: ['For Sale', 'Luxury'],
  },
  // --- Additional Tete ---
  {
    id: '27',
    title: 'Matundo River Bend Home',
    location: 'Matundo, Tete',
    city: 'Tete',
    price: 2500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 280,
    images: [IMG.house1, IMG.detail1, IMG.kitchen1],
    description: 'A quiet riverside retreat in Tete, featuring advanced cooling systems and a private pool.',
    amenities: ['River View', 'Swimming Pool', 'Advanced AC', 'Backup Power'],
    hostId: 'agent-9',
    tags: ['Rent', 'Riverside'],
  },
  {
    id: '28',
    title: 'Tete Bridge Executive Suites',
    location: 'Central Tete',
    city: 'Tete',
    price: 1800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 1,
    area: 120,
    images: [IMG.apt1, IMG.detail2, IMG.loft1],
    description: 'Modern executive suites near the Tete bridge, offering easy access to the business district.',
    amenities: ['WiFi', 'Parking', '24/7 Security', 'Gym Access'],
    hostId: 'agent-9',
    tags: ['Rent', 'Executive'],
  },
  // --- Additional Pemba ---
  {
    id: '29',
    title: 'Murrebue Beach Villa',
    location: 'Murrebue, Pemba',
    city: 'Pemba',
    price: 4500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 3,
    area: 350,
    images: [IMG.villa2, IMG.detail3, IMG.bungalow1],
    description: 'A world-class kite-surfing retreat on the white sands of Murrebue beach in Pemba.',
    amenities: ['Beachfront', 'Infinity Pool', 'Kite Surf Storage', 'Chef Service'],
    hostId: 'agent-12',
    tags: ['Rent', 'Beachfront'],
  },
  {
    id: '30',
    title: 'Pemba Marina View Apt',
    location: 'Marina District, Pemba',
    city: 'Pemba',
    price: 1200,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 145,
    images: [IMG.apt1, IMG.detail4, IMG.kitchen1],
    description: 'Modern apartment overlooking the Pemba marina. Perfect for professionals in the energy sector.',
    amenities: ['Sea View', 'Parking', 'Security', 'Balcony'],
    hostId: 'agent-5',
    tags: ['Rent', 'Sea View'],
  },
];

// ─── Agents ───────────────────────────────────────────────────────────────────
export const agents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Ricardo Santos',
    initials: 'RS',
    title: 'Premier Curator',
    location: 'Maputo City',
    rating: 4.9,
    reviewCount: 120,
    isFeatured: true,
    isVerified: true,
    avatar: IMG.agent1,
    bio: '"I specialize in sourcing the most exclusive architectural gems in Mozambique. My goal is to provide a seamless, high-touch residential experience for the discerning expatriate and local professional."',
    yearsExperience: 5,
    specializations: ['Luxury Villas', 'Expat Relocations', 'Polana District'],
  },
  {
    id: 'agent-2',
    name: 'Elena Matusse',
    initials: 'EM',
    title: 'Senior Partner',
    location: 'Matola',
    rating: 5.0,
    reviewCount: 98,
    isFeatured: true,
    isVerified: true,
    avatar: IMG.agent2,
    bio: 'With deep roots in Mozambican real estate, I provide unparalleled market insight and negotiation expertise across the greater Maputo area.',
    yearsExperience: 8,
    specializations: ['Residential Sales', 'Investment Properties', 'Matola Market'],
  },
  {
    id: 'agent-3',
    name: 'Antonio Vilanculo',
    initials: 'AV',
    title: 'Luxury Advisor',
    location: 'Beira',
    rating: 4.8,
    reviewCount: 76,
    isFeatured: true,
    avatar: IMG.agent3,
    bio: 'Focused on Beira and the central coast, I connect buyers with extraordinary waterfront properties and development opportunities.',
    yearsExperience: 6,
    specializations: ['Waterfront Properties', 'Beira Central', 'Commercial'],
  },
  {
    id: 'agent-4',
    name: 'Sofia Tembe',
    initials: 'ST',
    title: 'Investment Specialist',
    location: 'Maputo City',
    rating: 4.9,
    reviewCount: 143,
    isFeatured: true,
    isVerified: true,
    avatar: IMG.agent4,
    bio: 'Passionate about connecting global investors with Mozambique\'s most promising real estate opportunities. Expert in yield analysis and portfolio management.',
    yearsExperience: 7,
    specializations: ['Investment Properties', 'Portfolio Management', 'Market Analysis'],
  },
  {
    id: 'agent-5',
    name: 'Lucas Mondlane',
    initials: 'LM',
    title: 'Leasing Agent',
    location: 'Vilanculos',
    rating: 4.7,
    reviewCount: 55,
    isFeatured: true,
    avatar: IMG.agent5,
    bio: 'Specialist in the stunning northern coast — from Vilanculos to the Quirimbas Archipelago. I help renters and buyers find their perfect beach escape.',
    yearsExperience: 4,
    specializations: ['Short Stays', 'Beach Properties', 'Northern Coast'],
  },
  {
    id: 'agent-6',
    name: 'Sara Langa',
    initials: 'SL',
    title: 'Relocation Expert',
    location: 'Maputo City',
    rating: 4.9,
    reviewCount: 112,
    isFeatured: true,
    isVerified: true,
    avatar: IMG.agent6,
    bio: 'Dedicated to making international and domestic relocations to Mozambique smooth and successful. Fluent in Portuguese, English and French.',
    yearsExperience: 9,
    specializations: ['Expat Relocations', 'Corporate Leasing', 'Furnished Rentals'],
  },
  // All Agents (A-Z list)
  {
    id: 'agent-7',
    name: 'Abel Dimande',
    initials: 'AD',
    title: 'Commercial Broker',
    location: 'Matola',
    rating: 4.5,
    reviewCount: 34,
    specializations: ['Commercial Real Estate', 'Land Sales'],
  },
  {
    id: 'agent-8',
    name: 'Bento Jose',
    initials: 'BJ',
    title: 'Residential Specialist',
    location: 'Beira',
    rating: 4.6,
    reviewCount: 42,
    specializations: ['Residential Sales', 'First-Time Buyers'],
  },
  {
    id: 'agent-9',
    name: 'Carla Mutola',
    initials: 'CM',
    title: 'Luxury Rentals',
    location: 'Tete',
    rating: 4.9,
    reviewCount: 67,
    specializations: ['Luxury Rentals', 'Corporate Housing'],
  },
  {
    id: 'agent-10',
    name: 'Daniel Chissano',
    initials: 'DC',
    title: 'Rural Land Expert',
    location: 'Nampula',
    rating: 4.4,
    reviewCount: 28,
    specializations: ['Agricultural Land', 'Rural Properties'],
  },
  {
    id: 'agent-11',
    name: 'Ester Gove',
    initials: 'EG',
    title: 'Retail Specialist',
    location: 'Maputo City',
    rating: 4.8,
    reviewCount: 81,
    specializations: ['Retail Spaces', 'Commercial Leasing'],
  },
  {
    id: 'agent-12',
    name: 'Feliciano Sitoe',
    initials: 'FS',
    title: 'Beachfront Luxury',
    location: 'Pemba',
    rating: 4.7,
    reviewCount: 59,
    specializations: ['Beachfront Properties', 'Luxury Villas'],
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
export function getPropertyById(id: string): Property | undefined {
  return properties.find((p) => p.id === id);
}

export function getAgentById(id: string): Agent | undefined {
  return agents.find((a) => a.id === id);
}

export function getFeaturedProperties(): Property[] {
  return properties.filter((p) => p.isFeatured || p.isPremium).slice(0, 6);
}

export function getPropertiesByCity(city: string): Property[] {
  return properties.filter((p) => p.city.toLowerCase() === city.toLowerCase());
}

export function getFeaturedAgents(): Agent[] {
  return agents.filter((a) => a.isFeatured);
}

export function formatPrice(price: number, unit: Property['priceUnit']): string {
  const formatted = new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(price);

  switch (unit) {
    case 'monthly': return `${formatted}/mo`;
    case 'nightly': return `${formatted}/night`;
    case 'sale': return formatted;
    default: return formatted;
  }
}
