export const agents = [
  {
    id: 'agent-1',
    name: 'Ricardo Santos',
    initials: 'RS',
    title: 'Premier Agent',
    location: 'Maputo City',
    rating: 4.9,
    reviewCount: 120,
    isFeatured: true,
    isVerified: true,
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop',
    bio: '"I specialize in sourcing the most exclusive architectural gems in Mozambique. My goal is to provide a seamless, high-touch residential experience for the discerning expatriate and local professional."',
    yearsExperience: 5,
    specializations: ['Luxury Villas', 'Expat Relocations', 'Polana District'],
    email: 'agent-1@houseinmoz.com',
    password: 'password123', // In real app, this will be hashed
    role: 'AGENT',
  },
  {
    id: 'agent-2',
    name: 'Elena Matusse',
    initials: 'EM',
    title: 'Senior Partner',
    location: 'Matola',
    rating: 5.0,
    reviewCount: 98,
    isFeatured: true,
    isVerified: true,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop',
    bio: 'With deep roots in Mozambican real estate, I provide unparalleled market insight and negotiation expertise across the greater Maputo area.',
    yearsExperience: 8,
    specializations: ['Residential Sales', 'Investment Properties', 'Matola Market'],
    email: 'agent-2@houseinmoz.com',
    password: 'password123',
    role: 'AGENT',
  },
  {
    id: 'admin-1',
    name: 'System Administrator',
    initials: 'SA',
    title: 'Platform Director',
    location: 'Maputo HQ',
    rating: 5.0,
    reviewCount: 0,
    isFeatured: false,
    isVerified: true,
    email: 'admin@houseinmoz.com',
    password: 'password123',
    role: 'ADMIN',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop',
    bio: 'Overseeing the growth and excellence of the HouseinMozambique platform.',
    yearsExperience: 10,
    specializations: ['Platform Oversight', 'Strategic Planning'],
  },
  {
    id: 'agent-3',
    name: 'Antonio Vilanculo',
    initials: 'AV',
    title: 'Luxury Advisor',
    location: 'Beira',
    rating: 4.8,
    reviewCount: 76,
    isFeatured: true,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop',
    bio: 'Focused on Beira and the central coast, I connect buyers with extraordinary waterfront properties.',
    yearsExperience: 6,
    specializations: ['Waterfront Properties', 'Beira Central'],
    email: 'agent-3@houseinmoz.com',
    password: 'password123',
    role: 'AGENT',
  },
  {
    id: 'agent-4',
    name: 'Sofia Chivambo',
    initials: 'SC',
    title: 'Consultant Partner',
    location: 'Inhambane / Tofo',
    rating: 4.9,
    reviewCount: 45,
    isFeatured: true,
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=200&auto=format&fit=crop',
    bio: 'Residing in Tofo, I help clients find their beachside dream homes and investment properties in the Inhambane province.',
    yearsExperience: 4,
    specializations: ['Beachfront Villas', 'Tourism Investment', 'Tofo / Barra'],
    email: 'agent-4@houseinmoz.com',
    password: 'password123',
    role: 'AGENT',
  },
  {
    id: 'agent-5',
    name: 'David Matsinhe',
    initials: 'DM',
    title: 'Commercial Specialist',
    location: 'Pemba / North',
    rating: 4.7,
    reviewCount: 32,
    isFeatured: true,
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop',
    bio: 'Focused on the Cabo Delgado region, I specialize in commercial assets and logistics-related real estate.',
    yearsExperience: 7,
    specializations: ['Commercial Space', 'Industrial Land', 'Pemba Logistics'],
    email: 'agent-5@houseinmoz.com',
    password: 'password123',
    role: 'AGENT',
  },
  {
    id: 'agent-6',
    name: 'Isabel Mondlane',
    initials: 'IM',
    title: 'Residential Expert',
    location: 'Maputo Central',
    rating: 5.0,
    reviewCount: 112,
    isFeatured: true,
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?q=80&w=200&auto=format&fit=crop',
    bio: 'Personalized service for residential acquisitions in Maputo\'s core neighborhoods.',
    yearsExperience: 9,
    specializations: ['Sommerschield', 'Polana', 'Condominium Living'],
    email: 'agent-6@houseinmoz.com',
    password: 'password123',
    role: 'AGENT',
  },
  {
    id: 'agent-7',
    name: 'Marcus Nhaca',
    initials: 'MN',
    title: 'Land Specialist',
    location: 'Marracuene / Bilene',
    rating: 4.6,
    reviewCount: 28,
    isFeatured: true,
    isVerified: true,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    bio: 'Connecting developers with prime land opportunities in the expanding outskirts of Maputo.',
    yearsExperience: 5,
    specializations: ['Land Development', 'Agricultural Plots', 'Vacation Homes'],
    email: 'agent-7@houseinmoz.com',
    password: 'password123',
    role: 'AGENT',
  },
];

export const properties = [
  // MAPUTO
  {
    id: '1',
    title: 'Modern 3BR Villa in Polana',
    location: 'Polana Cimento, Maputo',
    city: 'Maputo',
    price: 4500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 3,
    area: 450,
    rating: 4.95,
    reviewCount: 12,
    isFeatured: true,
    isSuperhost: true,
    isRareFind: true,
    isPremium: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1564013359540-431dd1d9ed85?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1556911220-e15595b6a581?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1505691938895-1758d7eaa511?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba934f246?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Experience the pinnacle of Maputo living in this architecturally significant villa located in the heart of the historic Polana district.',
    amenities: ['WiFi', 'Security', 'Pool', 'Garden', 'Furnished'],
    hostId: 'agent-1',
  },
  {
    id: '2',
    title: 'Luxury Apartment with Ocean View',
    location: 'Sommerschield 2, Maputo',
    city: 'Maputo',
    price: 3500,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 180,
    isFeatured: true,
    isNew: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Breathtaking ocean views and modern minimalist design in Maputo\'s most prestigious neighborhood.',
    amenities: ['WiFi', 'Gym', 'Parking', 'Concierge'],
    hostId: 'agent-1',
  },
  {
    id: '3',
    title: 'Contemporary Townhouse',
    location: 'Costa do Sol, Maputo',
    city: 'Maputo',
    price: 2500,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 300,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0bb2a6c3e?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154542-a8436342e431?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Ideal for families, this spacious townhouse offers secure living near the beach.',
    amenities: ['Garden', 'Security', 'Parking'],
    hostId: 'agent-1',
  },

  // MATOLA
  {
    id: '4',
    title: 'Spacious Family Home in Matola',
    location: 'Matola C, Maputo Province',
    city: 'Matola',
    price: 1500,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 5,
    bathrooms: 4,
    area: 600,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613545325278-f24b0cae1224?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Perfect for large families, featuring a big yard and proximity to international schools.',
    amenities: ['Pool', 'Garden', 'Guest House'],
    hostId: 'agent-2',
  },
  {
    id: '5',
    title: 'Matola Executive Estate',
    location: 'Witbank Road, Matola',
    city: 'Matola',
    price: 450000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 4,
    area: 800,
    isPremium: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A masterpiece of contemporary architecture situated in a quiet, high-security area of Matola.',
    amenities: ['Home Cinema', 'Borehole', 'Pool', 'Garage'],
    hostId: 'agent-2',
  },

  // BEIRA
  {
    id: '6',
    title: 'Beachfront Plot Beira',
    location: 'Macuti Beach, Beira',
    city: 'Beira',
    price: 200000,
    priceUnit: 'sale',
    type: 'Land',
    listingType: 'Buy',
    bedrooms: 0,
    bathrooms: 0,
    area: 2000,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1506929113674-bf7ef86cc35e?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Prime development opportunity for a boutique hotel or luxury residence directly on Macuti Beach.',
    amenities: ['Ocean Front'],
    hostId: 'agent-3',
  },
  {
    id: '7',
    title: 'Restored Colonial Mansion',
    location: 'Ponta Gea, Beira',
    city: 'Beira',
    price: 350000,
    priceUnit: 'sale',
    type: 'House',
    listingType: 'Buy',
    bedrooms: 6,
    bathrooms: 4,
    area: 500,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1554995207-c18c20360a59?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513584684031-43d1ab3d3171?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Stunning historical property meticulously restored, honoring Beira\'s architectural heritage.',
    amenities: ['High Ceilings', 'Garden', 'Balcony'],
    hostId: 'agent-3',
  },

  // VILANCULOS / TOFO
  {
    id: '8',
    title: 'Luxury Beach Resort Villa',
    location: 'Vilanculos Coast',
    city: 'Vilanculos',
    price: 1200,
    priceUnit: 'nightly',
    type: 'Villa',
    listingType: 'Short Stay',
    bedrooms: 5,
    bathrooms: 5,
    area: 400,
    isFeatured: true,
    isGuestFavorite: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544161515-4af6b1d462c2?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'The ultimate vacation home in the Bazaruto Archipelago. Private beach access and full staffing.',
    amenities: ['Private Chef', 'Boat Access', 'Infinity Pool', 'Spa'],
    hostId: 'agent-3',
  },
  {
    id: '9',
    title: 'Tofo Surf Shack',
    location: 'Tofo Beach, Inhambane',
    city: 'Inhambane',
    price: 150,
    priceUnit: 'nightly',
    type: 'House',
    listingType: 'Short Stay',
    bedrooms: 2,
    bathrooms: 1,
    area: 120,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1473116763249-2faaef81ccda?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Live the Tofo dream. Simple, beautiful, and steps away from the best surf breaks in Africa.',
    amenities: ['Hammocks', 'Outdoor Shower', 'Solar Power'],
    hostId: 'agent-2',
  },

  // PEMBA / NORTH
  {
    id: '10',
    title: 'Pemba Bay Eco-Lodge',
    location: 'Pemba Bay, Cabo Delgado',
    city: 'Pemba',
    price: 1200000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 12,
    bathrooms: 14,
    area: 5000,
    isPremium: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1540541338287-41700207dee6?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1544161515-4af6b1d462c2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Turnkey eco-resort opportunity in one of the world\'s largest natural bays.',
    amenities: ['Restaurant', 'Dive Center', 'Solar Grid'],
    hostId: 'agent-1',
  },
  {
    id: '11',
    title: 'Modern Apartment Complex',
    location: 'Expansão, Pemba',
    city: 'Pemba',
    price: 2800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 150,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Ideal corporate housing for the growing industry in Pemba. High security and back-up power.',
    amenities: ['Security', 'Backup Gen', 'AC'],
    hostId: 'agent-1',
  },
  
  // EXTRA PENDING MODERATION LISTINGS
  {
    id: '12',
    title: 'Secret Forest Villa',
    location: 'Marracuene',
    city: 'Maputo',
    price: 3800,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    status: 'PENDING',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A secluded sanctuary for those who value privacy and nature.',
    amenities: ['Forest Trails', 'Privacy'],
    hostId: 'agent-1',
  },
  {
    id: '13',
    title: 'Downtown Studio',
    location: 'Bairro Central, Maputo',
    city: 'Maputo',
    price: 800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    status: 'REJECTED',
    images: [
      'https://images.unsplash.com/photo-1536376074432-ca0245025be0?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Compact urban living. Note: This listing was rejected due to incomplete documentation.',
    amenities: ['Elevator'],
    hostId: 'agent-2',
  },
  // AUCTION PROPERTIES
  {
    id: '14',
    title: 'Historic Port Warehouse Auction',
    location: 'Baixa, Maputo Port',
    city: 'Maputo',
    price: 1500000,
    priceUnit: 'sale',
    type: 'Commercial',
    listingType: 'Auction',
    bedrooms: 0,
    bathrooms: 4,
    area: 2500,
    isFeatured: true,
    isPremium: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1577412647305-991150c7d163?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Rare opportunity to acquire a significant piece of Maputo\'s maritime history. Bidding starts at $1.5M. High potential for luxury loft conversion.',
    amenities: ['Historical Status', 'Port Access', 'High Ceilings'],
    hostId: 'agent-1',
  },
  {
    id: '15',
    title: 'Secluded Clifftop Estate Auction',
    location: 'Ponta do Ouro Cliffs',
    city: 'Ponta do Ouro',
    price: 850000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Auction',
    bedrooms: 6,
    bathrooms: 6,
    area: 1200,
    isFeatured: true,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Breathtaking 360-degree views of the Indian Ocean. This estate will be auctioned to the highest bidder. Register now for the selection process.',
    amenities: ['Ocean View', 'Helipad', 'Infinity Pool'],
    hostId: 'agent-2',
  },

  // --- NEW PROPERTIES TO SATISFY "AT LEAST 6 PER LOCATION" ---

  // MAPUTO (Current: 1, 2, 3, 14. Need 2 more)
  {
    id: '16',
    title: 'Sommerschield Executive Residence',
    location: 'Sommerschield, Maputo',
    city: 'Maputo',
    price: 5500,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 5,
    bathrooms: 4,
    area: 550,
    status: 'PUBLISHED',
    isFeatured: true,
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop'],
    description: 'A grand residence with high ceilings and a private swimming pool.',
    amenities: ['Pool', 'Security', 'AC'],
    hostId: 'agent-6',
  },
  {
    id: '17',
    title: 'Skyline Penthouse',
    location: 'Av. Julius Nyerere, Maputo',
    city: 'Maputo',
    price: 4000,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 3,
    area: 250,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=1200&auto=format&fit=crop'],
    description: 'Experience panoramic city views from this luxury penthouse.',
    amenities: ['Concierge', 'Gym', 'View'],
    hostId: 'agent-1',
  },

  // BEIRA (Current: 6, 7. Need 4 more)
  {
    id: '18',
    title: 'Macuti Beachfront House',
    location: 'Macuti, Beira',
    city: 'Beira',
    price: 2500,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 320,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?q=80&w=1200&auto=format&fit=crop'],
    description: 'Modern family home just steps away from the beach.',
    amenities: ['Ocean View', 'Garden', 'AC'],
    hostId: 'agent-3',
  },
  {
    id: '19',
    title: 'Ponta Gea Modern Flat',
    location: 'Ponta Gea, Beira',
    city: 'Beira',
    price: 1200,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 1,
    area: 110,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop'],
    description: 'Conveniently located apartment in the heart of Beira.',
    amenities: ['Elevator', 'Security'],
    hostId: 'agent-3',
  },
  {
    id: '20',
    title: 'Industrial Warehouse Baixa',
    location: 'Baixa, Beira',
    city: 'Beira',
    price: 15000,
    priceUnit: 'monthly',
    type: 'Commercial',
    listingType: 'Rent',
    bedrooms: 0,
    bathrooms: 2,
    area: 1200,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop'],
    description: 'Spacious warehouse ideal for logistics and storage.',
    amenities: ['Parking', 'Loading Dock'],
    hostId: 'agent-3',
  },
  {
    id: '21',
    title: 'Beira Port View Villa',
    location: 'Port District, Beira',
    city: 'Beira',
    price: 280000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 5,
    bathrooms: 4,
    area: 450,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1613977257363-707ba934f246?q=80&w=1200&auto=format&fit=crop'],
    description: 'A prestigious villa with views of the bustling Beira port.',
    amenities: ['Pool', 'Huge Terrace'],
    hostId: 'agent-3',
  },

  // NAMPULA (Current: 0. Need 6)
  {
    id: '22',
    title: 'Nampula Business Hub Apartment',
    location: 'Central Nampula',
    city: 'Nampula',
    price: 1500,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 140,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Perfect for professionals working in the northern economic hub.',
    amenities: ['Security', 'Parking', 'AC'],
    hostId: 'agent-5',
  },
  {
    id: '23',
    title: 'Grand Palace Nampula',
    location: 'Muatala, Nampula',
    city: 'Nampula',
    price: 320000,
    priceUnit: 'sale',
    type: 'House',
    listingType: 'Buy',
    bedrooms: 5,
    bathrooms: 4,
    area: 600,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1200&auto=format&fit=crop'],
    description: 'A large estate house with excessive lawn and garden space.',
    amenities: ['Garden', 'Borehole', 'Separate SQ'],
    hostId: 'agent-5',
  },
  {
    id: '24',
    title: 'Northern Sky Apartment',
    location: 'Central, Nampula',
    city: 'Nampula',
    price: 1800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop'],
    description: 'Modern finishing in a secure residential complex.',
    amenities: ['Security', 'Elevator'],
    hostId: 'agent-5',
  },
  {
    id: '25',
    title: 'Nampula Industrial Plot',
    location: 'Industrial Zone, Nampula',
    city: 'Nampula',
    price: 450000,
    priceUnit: 'sale',
    type: 'Land',
    listingType: 'Buy',
    bedrooms: 0,
    bathrooms: 0,
    area: 5000,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop'],
    description: 'Prime land for industrial or warehouse development.',
    amenities: ['Road Access', 'Electricity Connection'],
    hostId: 'agent-5',
  },
  {
    id: '26',
    title: 'Cozy Muatala House',
    location: 'Muatala, Nampula',
    city: 'Nampula',
    price: 900,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 200,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1580587767303-9bb6fa099951?q=1200&w=1200&auto=format&fit=crop'],
    description: 'Charming family home in a quiet neighborhood.',
    amenities: ['Fence', 'Garden'],
    hostId: 'agent-5',
  },
  {
    id: '27',
    title: 'Executive Stay Nampula',
    location: 'Nampula City',
    city: 'Nampula',
    price: 150,
    priceUnit: 'nightly',
    type: 'Apartment',
    listingType: 'Short Stay',
    bedrooms: 2,
    bathrooms: 2,
    area: 130,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1493238792000-8113da705763?q=80&w=1200&auto=format&fit=crop'],
    description: 'High-end short-term accommodation for business travelers.',
    amenities: ['Daily Cleaning', 'WiFi', 'Breakfast'],
    hostId: 'agent-5',
  },

  // TETE (Current: 0. Need 6)
  {
    id: '28',
    title: 'Zambeze River Villa',
    location: 'Riverside, Tete',
    city: 'Tete',
    price: 3000,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 400,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba934f246?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672033935-71e9975b20cd?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Stunning views of the Zambeze River in Tete\'s primary residential area.',
    amenities: ['River View', 'Pool', 'Backup Power'],
    hostId: 'agent-5',
  },
  {
    id: '29',
    title: 'Mining Executive Compound',
    location: 'Matundo, Tete',
    city: 'Tete',
    price: 4500,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 5,
    bathrooms: 4,
    area: 650,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=1200&auto=format&fit=crop'],
    description: 'High-security compound ideal for expatriate staff.',
    amenities: ['Gated', 'Pool', 'Gym'],
    hostId: 'agent-5',
  },
  {
    id: '30',
    title: 'Modern Matundo Flat',
    location: 'Matundo, Tete',
    city: 'Tete',
    price: 1200,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1574362848149-11496d93a7c7?q=80&w=1200&auto=format&fit=crop'],
    description: 'New build apartment with reliable services.',
    amenities: ['AC', 'Security'],
    hostId: 'agent-5',
  },
  {
    id: '31',
    title: 'Riverside Commercial Office',
    location: 'Baixa, Tete',
    city: 'Tete',
    price: 2500,
    priceUnit: 'monthly',
    type: 'Commercial',
    listingType: 'Rent',
    bedrooms: 0,
    bathrooms: 3,
    area: 250,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop'],
    description: 'Prime office space for companies operative in the mining sector.',
    amenities: ['Fiber Internet', 'Parking'],
    hostId: 'agent-5',
  },
  {
    id: '32',
    title: 'Tete City Center Apartment',
    location: 'Central, Tete',
    city: 'Tete',
    price: 1500,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    status: 'PUBLISHED',
    images: ['https://images.unsplash.com/photo-1460317442991-0ec209397118?q=80&w=1200&auto=format&fit=crop'],
    description: 'Spacious apartment near the main government and business buildings.',
    amenities: ['Security', 'AC'],
    hostId: 'agent-5',
  },
  {
    id: '33',
    title: 'Industrial Plot Matundo',
    location: 'Matundo, Tete',
    city: 'Tete',
    price: 200000,
    priceUnit: 'sale',
    type: 'Land',
    listingType: 'Buy',
    bedrooms: 0,
    bathrooms: 0,
    area: 3000,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1504307651254-35680f356dfd?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Versatile land plot ready for development.',
    amenities: ['Fenced', 'Electricity'],
    hostId: 'agent-5',
  },

  // PEMBA (Current: 10, 11. Need 4 more)
  {
    id: '34',
    title: 'Wimbe Beach Villa',
    location: 'Wimbe Beach, Pemba',
    city: 'Pemba',
    price: 2200,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 350,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Charming beachfront villa in Pemba\'s most famous leisure area.',
    amenities: ['Beach Access', 'AC', 'Security'],
    hostId: 'agent-5',
  },
  {
    id: '35',
    title: 'Maringanha Executive Residence',
    location: 'Maringanha, Pemba',
    city: 'Pemba',
    price: 3500,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 5,
    bathrooms: 5,
    area: 500,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1512914890251-2f96a9b092e3?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0bb2a6c3e?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Modern luxury home in a secure, growing enclave of Pemba.',
    amenities: ['Pool', 'Huge Yard', 'Security'],
    hostId: 'agent-5',
  },
  {
    id: '36',
    title: 'Corporate HQ Pemba',
    location: 'Baixa, Pemba',
    city: 'Pemba',
    price: 5000,
    priceUnit: 'monthly',
    type: 'Commercial',
    listingType: 'Rent',
    bedrooms: 0,
    bathrooms: 4,
    area: 800,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Full-building commercial space ideal for international energy firms.',
    amenities: ['Fiber Internet', 'Security', 'Backup Power'],
    hostId: 'agent-5',
  },
  {
    id: '37',
    title: 'Pemba View Apartment',
    location: 'Central, Pemba',
    city: 'Pemba',
    price: 1800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'High-elevation apartment with stunning bay views.',
    amenities: ['View', 'Security'],
    hostId: 'agent-5',
  },

  // INHAMBANE (Current: 9. Need 5 more)
  {
    id: '38',
    title: 'Tofinho Clifftop Villa',
    location: 'Tofinho, Inhambane',
    city: 'Inhambane',
    price: 350000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1510798831971-661eb04b3739?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Incredible clifftop estate overlooking the surfing breaks of Tofinho.',
    amenities: ['Ocean View', 'Garden'],
    hostId: 'agent-4',
  },
  {
    id: '39',
    title: 'Inhambane City Heritage House',
    location: 'Baixa, Inhambane',
    city: 'Inhambane',
    price: 180000,
    priceUnit: 'sale',
    type: 'House',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 2,
    area: 220,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1554995207-c18c20360a59?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513584684031-43d1ab3d3171?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A beautifully preserved historical house in the "City of Palms".',
    amenities: ['History', 'Central'],
    hostId: 'agent-4',
  },
  {
    id: '40',
    title: 'Barra Beach Retreat',
    location: 'Barra, Inhambane',
    city: 'Inhambane',
    price: 250,
    priceUnit: 'nightly',
    type: 'Villa',
    listingType: 'Short Stay',
    bedrooms: 3,
    bathrooms: 3,
    area: 200,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Modern luxury retreat on the dunes of Barra beach.',
    amenities: ['Pool', 'WiFi', 'Beach Access'],
    hostId: 'agent-4',
  },
  {
    id: '41',
    title: 'Palm Grove Apartment',
    location: 'Tofo, Inhambane',
    city: 'Inhambane',
    price: 800,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Simple and clean apartment for digital nomads in Tofo.',
    amenities: ['WiFi', 'Backup Power'],
    hostId: 'agent-4',
  },
  {
    id: '42',
    title: 'Eco-Cabin Tofo',
    location: 'Outside Tofo, Inhambane',
    city: 'Inhambane',
    price: 80,
    priceUnit: 'nightly',
    type: 'House',
    listingType: 'Short Stay',
    bedrooms: 1,
    bathrooms: 1,
    area: 60,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1433086966358-54859d0ed716?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1469474968028-56623f02e42e?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Off-grid eco living in the middle of nature.',
    amenities: ['Solar', 'Nature Trails'],
    hostId: 'agent-4',
  },

  // --- ADDITIONAL PROPERTIES FOR SMALLER LOCATIONS ---

  // MATOLA (Need 2 more)
  {
    id: '43',
    title: 'Modern Matola Apartment',
    location: 'Matola Central',
    city: 'Matola',
    price: 1200,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Chic urban living in the heart of Matola city.',
    amenities: ['Elevator', 'Security', 'AC'],
    hostId: 'agent-2',
  },
  {
    id: '44',
    title: 'Matola Garden House',
    location: 'Bairro da Liberdade, Matola',
    city: 'Matola',
    price: 1800,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 250,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1580587767303-9bb6fa099951?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1628592102751-ba83b03144e3?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Beautiful garden home with plenty of outdoor space.',
    amenities: ['Garden', 'Borehole', 'Security'],
    hostId: 'agent-2',
  },

  // VILANCULOS (Need 3 more)
  {
    id: '45',
    title: 'Vilanculos Bay View Apartment',
    location: 'Vilanculos Town',
    city: 'Vilanculos',
    price: 1500,
    priceUnit: 'monthly',
    type: 'Apartment',
    listingType: 'Rent',
    bedrooms: 2,
    bathrooms: 2,
    area: 140,
    status: 'PUBLISHED',
    isFeatured: true,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Modern apartment with sweeping views of the Bazaruto Archipelago.',
    amenities: ['View', 'Security', 'Pool'],
    hostId: 'agent-3',
  },
  {
    id: '46',
    title: 'Fisherman\'s Dream Cottage',
    location: 'North Beach, Vilanculos',
    city: 'Vilanculos',
    price: 180,
    priceUnit: 'nightly',
    type: 'House',
    listingType: 'Short Stay',
    bedrooms: 2,
    bathrooms: 1,
    area: 110,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Quaint cottage on the water\'s edge. Perfect for a quiet get-away.',
    amenities: ['Beach Access', 'Self-Catering', 'Boat Launch'],
    hostId: 'agent-3',
  },
  {
    id: '47',
    title: 'Mango Grove Villa',
    location: 'Coastal Road, Vilanculos',
    city: 'Vilanculos',
    price: 450000,
    priceUnit: 'sale',
    type: 'Villa',
    listingType: 'Buy',
    bedrooms: 4,
    bathrooms: 3,
    area: 400,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba934f246?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-11613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'A luxurious villa surrounded by mature mango trees, just minutes from the airport.',
    amenities: ['Pool', 'Huge Orchard', 'Guest Wing'],
    hostId: 'agent-3',
  },

  // PONTA DO OURO (Need 3 more)
  {
    id: '48',
    title: 'Dolphin View Chalet',
    location: 'Main Hill, Ponta do Ouro',
    city: 'Ponta do Ouro',
    price: 120,
    priceUnit: 'nightly',
    type: 'House',
    listingType: 'Short Stay',
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1464146072144-62447730db4e?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1433086966358-54859d0ed716?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Rustic charm with a modern twist. Great views of the bay.',
    amenities: ['View', 'Deck', 'Braai Area'],
    hostId: 'agent-2',
  },
  {
    id: '49',
    title: 'Ponta Surf Lodge',
    location: 'Village Center, Ponta do Ouro',
    city: 'Ponta do Ouro',
    price: 180000,
    priceUnit: 'sale',
    type: 'Commercial',
    listingType: 'Buy',
    bedrooms: 8,
    bathrooms: 8,
    area: 600,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Turnkey business opportunity. Established lodge in the heart of the village.',
    amenities: ['Pool', 'Bar', 'Dive Center'],
    hostId: 'agent-2',
  },
  {
    id: '50',
    title: 'The Sands Villa',
    location: 'Dune Area, Ponta do Ouro',
    city: 'Ponta do Ouro',
    price: 3200,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 320,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba934f246?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-11613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Exclusive villa on the dunes. Modern, secure, and private.',
    amenities: ['Pool', 'Security', 'Ocean View'],
    hostId: 'agent-2',
  },

  // MARRACUENE (Need 3 more)
  {
    id: '51',
    title: 'River Bend Estate',
    location: 'Incomati Riverfront, Marracuene',
    city: 'Marracuene',
    price: 2500,
    priceUnit: 'monthly',
    type: 'House',
    listingType: 'Rent',
    bedrooms: 4,
    bathrooms: 3,
    area: 380,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1518780664697-55e3ad937233?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1628592102751-ba83b03144e3?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1580587767303-9bb6fa099951?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Tranquil living on the banks of the Incomati River.',
    amenities: ['River View', 'Garden', 'Private Jetty'],
    hostId: 'agent-7',
  },
  {
    id: '52',
    title: 'Marracuene Vacation Plot',
    location: 'Macaneta Road, Marracuene',
    city: 'Marracuene',
    price: 85000,
    priceUnit: 'sale',
    type: 'Land',
    listingType: 'Buy',
    bedrooms: 0,
    bathrooms: 0,
    area: 1200,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1519046904884-53103b34b206?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1506929113674-bf7ef86cc35e?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Prime plot ready for building your dream holiday home.',
    amenities: ['Fenced', 'Electricity Ready'],
    hostId: 'agent-7',
  },
  {
    id: '53',
    title: 'Modern Marracuene Villa',
    location: 'Vila de Marracuene',
    city: 'Marracuene',
    price: 1800,
    priceUnit: 'monthly',
    type: 'Villa',
    listingType: 'Rent',
    bedrooms: 3,
    bathrooms: 2,
    area: 280,
    status: 'PUBLISHED',
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1613977257363-707ba934f246?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-11613490493576-7fde63acd811?q=80&w=1200&auto=format&fit=crop',
    ],
    description: 'Secure and modern living just a short drive from Maputo.',
    amenities: ['Pool', 'Security', 'Modern Kitchen'],
    hostId: 'agent-7',
  },
];

